# Generated by Django 5.2.6 on 2025-09-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substitute',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='substitute',
            old_name='firest_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='substitute',
        ),
        migrations.AddField(
            model_name='customuser',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Myapp.substitute'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
