# Generated by Django 5.2.6 on 2025-09-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_rename_mail_substitute_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='users',
        ),
        migrations.AddField(
            model_name='customuser',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Myapp.substitute'),
        ),
    ]
