# Generated by Django 5.1.4 on 2025-09-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_customuser_balance_trasaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasaction',
            new_name='Transaction',
        ),
    ]
