# Generated by Django 5.1.4 on 2025-09-21 20:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_alter_customuser_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('SOCIALE', 'Sociale')], max_length=10),
        ),
    ]
