# Generated by Django 5.2.6 on 2025-09-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_credit_credittransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='interest_rate',
            new_name='interst_rate',
        ),
    ]
