# Generated by Django 5.2.6 on 2025-09-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_rename_interest_rate_credit_interst_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='interst_rate',
            new_name='interset_rate',
        ),
    ]
