# Generated by Django 5.2.6 on 2025-09-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_rename_interst_rate_credit_interset_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittransaction',
            old_name='credi',
            new_name='credit',
        ),
    ]
