# Generated by Django 5.2.6 on 2025-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_rename_credi_credittransaction_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
