# Generated by Django 5.2.6 on 2025-09-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_alter_credittransaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='reference',
            field=models.CharField(default=0, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
