# Generated by Django 5.2.6 on 2025-09-28 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_credittransaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('SOCIALE', 'Sociale'), ('ENVOIE', 'Envoi')], max_length=10),
        ),
        migrations.CreateModel(
            name='CashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('motid', models.CharField(default='Aucun motif', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashOutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Myapp.cashout')),
            ],
        ),
    ]
