# Generated by Django 5.2.6 on 2025-09-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0014_alter_transaction_transaction_type_cashout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashout',
            old_name='motid',
            new_name='motif',
        ),
    ]
