# Generated by Django 5.2.6 on 2025-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_rename_motid_cashout_motif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('SOCIALE', 'Sociale'), ('ENVOIE', 'Envoi'), ('ANNULATION', 'Annulation')], max_length=10),
        ),
    ]
