# Generated by Django 5.2.6 on 2025-10-04 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0016_cycle_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Crédit'), ('REMBOURSEMENT', 'Remboursement'), ('ANNULATION', 'Annulation')], max_length=15),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
