# Generated by Django 5.2.6 on 2025-10-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_alter_credittransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
