# Generated by Django 5.2.6 on 2025-10-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0018_customuser_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutdetail',
            name='reason',
            field=models.CharField(default='', max_length=255),
        ),
    ]
